/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface LoginRequestDTO {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}
