/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SendSmsRequestDtoDTO {
  /**
   * @minLength 1
   * @maxLength 11
   */
  from: string;
  /**
   * @minLength 1
   * @maxLength 160
   */
  message: string;
  /**
   * @minLength 1
   * @pattern ^\+[1-9]\d{1,14}$
   */
  to: string;
}
