/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */
import type { SmsImprovementDTO } from './smsImprovementDTO';

export interface SmsImproveResponseDTODTO {
  /** @nullable */
  improvements: SmsImprovementDTO[] | null;
}
