/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SmsImprovementDTO {
  /** @nullable */
  explanation: string | null;
  /** @nullable */
  improvedText: string | null;
}
