/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: v1
 */

export interface SmsMessageResponseDtoDTO {
  createdAt?: string;
  /** @nullable */
  errorMessage?: string | null;
  id?: string;
  /** @nullable */
  message?: string | null;
  sent?: boolean;
  /** @nullable */
  to?: string | null;
}
